EMAIL_PASSWORD = "csuh xxru wqdy mttt"
SPREADSHEET_ID = "1xLvrH6LN8Vw3dVzoguf6TkgRrsJvEpMl2Z8s8HAvrVA"

PAYPAL_CLIENT_ID = "AcdelUggufMf2uhaEFAAHGQV7SLku5nFOCJfqk93HpwnbHNo_gnQI17qJ2n0AScioVI120qLAnvo-ZLw"
PAYPAL_CLIENT_SECRET = "EHXBlKgRAyV9uWYA-rJyHkaLfWi88o9swhHTplRgtZ1bFJIayzVJCJx7uorv1zulPM2i3Mo4pfA9C4o9"
PAYPAL_MODE = "live"


[gcp_service_account]
type = "service_account"
project_id = "ahp2-486703"
private_key_id = "135ff08f7cd447f2894b18d5aa2ea998b12baa0e"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDVOFD2rcHKUQuS\nv8ECwZCBI8IZj1WUDKlO8K9LweF3rgjFJqAxS6jqtpDfohv5Kkp689wusOM3sT6R\nqxFQXHFPEd4W+VVrmvG4moV9kblmXIf7w08CLlu8ptRuBl0PuakSP/LU7B6T4shY\ni0QHdYK/P6KsUTwLlFHcO/8AzP0wHLuBfFya3mJaElUETr4Hp53168JoHXXWK8wE\nws2dr8Jk3IFDSwXT5eKFtrDZtv65pKgiUD1bguoqsfSiqeIkouvWlildHolIOKPz\ncYuOb5fz70yZQd5CmYh/3dP3OCOkU+wJnequu23vFcaiJ6COUSzFCQCkHo18aWbu\nP93zXkZrAgMBAAECggEABCDsCGrC5tz84WGPJjODTczYdFA/Mvevy5SDgG8Ho56e\nEts1nN6/LZRNZ9cmvYNhH9JbABhyveBTutRaKHkxxHsvFrjLO6MrbQyo6w6ITYAb\nLffRLtSg+B0u3daHtMc+i9jrJc5QpUJt6LEBpzdSScu8paOJCxxbHW2X+Xb+rBDJ\nR1a0K+2hEXPLl5JeQ0f/4LPZYRpJ5q1k+HK7Q1L4G8uJAm/xfSmC/ymeCMezri7A\nk1wnyq78E0scNGdrkbFZH/MkiSZ0vgZKRhdyGyC/hzlDGiFJPtjrIB84cqKsXb07\n/pagw7t/IIkyQfoa4EM978oTL6cusM4Iiu7Lew4LIQKBgQD/RsKLcUI6tfldHMnf\nRxgPSnoCDJ7kiDBvnSg4LJpU8DMrf2InPLazk/tBNoIHVxkf9UyzjTFQbScO8oYH\nuwXuwZXnjYjqhqxbdo34XcUX+sIrfQuSIoZIKSq61JhgPf0uD+irwkLzMQb28rrH\nsYSf6dpC1+mnIu7Uhp8aqiQZkQKBgQDV0wnNZ2FzefZ2hOEYhMtwq+ck1JoAqx+K\n1c9/Cb/OIjlpimzRdOOz89POX0agQmHSZCQwRMgRHFHoaJmryg8BQiKn1DnaX0wS\nWKIsZFbZjHvxBLuRSwLql/3TkPKs7JKCTEsQDH5bqzs7+zQwit8Rytb+APyL+bYD\nYelNtKVCOwKBgDINe8O/l07Ps28wX9ypoewNnFKeiuEgWu7nj6VECZax6jaTKXms\nC962G0O0Hla2GzUK8dkazBqK7Gef4evOHeGsj2nxdHEXqt/cJQYXzLdg8YV5ZTVo\nE5A+kiRD3wSv4t6PO/3Bf0MTz9vHyBuzkN+SCLumfifJT67YHoYp6h4hAoGBAJWL\nKmDgu7QyiV/soS0vusTLRTZqBmcPR1knHh6gJ+g34WVh7ac0FAiIMAs2cUOmCZpG\ndVTY1f+5icN8XHVcNNBRe8Fa2TdTzPVLzeg0KNWvvgMbpz7/ckO2F0y/JCoyrmi4\niQrpYfoksKHLl32XsllUPraY5AfVlimZcbzp6WZ/AoGAN1fKmElDjWeCQ3xb286o\nQr8cI0CSVfyp3EHMHgiAy5hSoYft2nUW14FOiiwHUgosHx7kCnlQkxq/FeioeBJO\n1r8aE5OYrrbsgSaS97TB56cjMhzXH0dx1rU93/2zeEAsdiWPy0fNSGnyUU/eVCzd\nNFVSAVN4Ctl6pPLfbUfoPCM=\n-----END PRIVATE KEY-----\n"
client_email = "ahp2-75@ahp2-486703.iam.gserviceaccount.com"
client_id = "114199138161368024816"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/ahp2-75%40ahp2-486703.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

LOG_SPREADSHEET_ID = "1jrnOMiqNwfoqMsK9mB4NxhUSI32UUmelfBDtWz9QFVU"
